SELECT SALARY.EMP_ID,SALARY.NAME,
	   SALARY.[TOTAL WORKED HOURS], 
	   IIF(MATCH.[PREVIOUS SALARY] = MATCH.[CURRENT SALARY], 'NO', 'YES')AS GOT_INCREMENT,
	   MATCH.[PREVIOUS SALARY],
	   MATCH.[CURRENT SALARY],
	   TACTIVITY.ACTIVITY_DESCRIPTION AS [LAST WORKED ACTIVITY], 
	   AD.ATTEN_END_HRS AS [HOURS WORKED ]
FROM T_ATTEN_DET AD
INNER JOIN
	(
	SELECT A.EMP_ID,
		   E.EMP_F_NAME + ' ' + COALESCE(E.EMP_M_NAME,'') + ' ' + COALESCE(E.EMP_L_NAME,'') AS NAME,
		   SUM(A.ATTEN_END_HRS) AS [TOTAL WORKED HOURS],
		   MAX(A.ATTEN_START_DATETIME) AS [LAST WORKED ACTIVITY]
	FROM T_EMP E
	INNER JOIN T_ATTEN_DET A
	ON
	E.EMP_ID = A.EMP_ID
	INNER JOIN T_ACTIVITY AC
	ON A.ACTIVITY_ID = AC.ACTIVITY_ID
	GROUP BY E.EMP_F_NAME + ' ' + COALESCE(E.EMP_M_NAME,'') + ' ' + COALESCE(E.EMP_L_NAME,''), A.EMP_ID
	)SALARY
ON AD.ATTEN_START_DATETIME = SALARY.[LAST WORKED ACTIVITY]
INNER JOIN T_ACTIVITY TACTIVITY
ON
AD.ACTIVITY_ID = TACTIVITY.ACTIVITY_ID
INNER JOIN 
(
SELECT T1.EMP_ID,
	   T1.NEW_SALARY AS [PREVIOUS SALARY],
	   T2.NEW_SALARY AS [CURRENT SALARY]
FROM T_SALARY T1
INNER JOIN T_SALARY T2
ON
T1.EMP_ID = T2.EMP_ID AND T1.CHANGED_DATE < T2.CHANGED_DATE
) MATCH
ON
SALARY.EMP_ID = MATCH.EMP_ID