USE SQLTEST;
--Ans 1.
	SELECT S.EMPLOYEEID,E.EMPLOYEENAME,S.PROJECTID,P.PROJECTNAME,
	SUM(HRS) AS HOURS
	FROM SCHEDULE S
	INNER JOIN EMPLOYEE E ON E.EMPLOYEEID = S.EMPLOYEEID
	INNER JOIN PROJECT P ON S.PROJECTID = P.PROJECTID
	GROUP BY S.EMPLOYEEID,E.EMPLOYEENAME,S.PROJECTID,P.PROJECTNAME
	ORDER BY S.EMPLOYEEID

--Ans 2.
	SELECT S.PROJECTID,P.DEPARTMENTID,D.DEPARTMENTNAME,SUM(HRS) AS HOURS
	FROM SCHEDULE S
	INNER JOIN PROJECT P ON S.PROJECTID = P.PROJECTID
	INNER JOIN DEPARTMENT D ON D.DEPARTMENTID =P.DEPARTMENTID
	GROUP BY S.PROJECTID,P.DEPARTMENTID,D.DEPARTMENTNAME
